### ISSUE TITLE
Building for itch.io

### ISSUE THREAD

**Issue by bonder** [phaserjs/template-vite#1]
The build task produces an index.html page that assumes the base directory is always the root of the server.

However, this causes 403 errors when uploading directly to itch.io.

Currently, I manually fix the references from '/' to './' just to get it working.

But I'm wondering if there should be a dedicated build itch.io script that would produce the correct dist output?

**Comment by bonder** [comment]
Copilot to the rescue. :)

      "build itch.io": "vite build --base=./"

Not sure if this should be its own script, or if the existing one should be changed to use relative pathing, or if the vite.config.js should be changed to set the base there.

**Comment by photonstorm** [comment]
Thanks Bruce. I think we should do both: Make the path relative by default (as that's the most likely requirement) and put the path in the config.

This will resolve it for Itch and any other host that runs off folders (which is lots!)

**Comment by gammafp** [comment]
Thank you, @bonder. 
Inside config files (vite/*) you can find the base: './' config, and works with itch.io and others hosts too.
